### ISSUE TITLE
Could you please upload your predcomputed CNN features on databases?

### ISSUE THREAD

**Issue by Sissuire** [jarikorhonen/cnn-tlvqm#2]
Thanks for your sharing.

In my computer, the Deep Learning Toolbox has not been installed. So, is it possible to upload your precomputed features in the databases? Thus I can directly use and evaluate the performance.

**Comment by jarikorhonen** [comment]
You can try these:

https://mega.nz/file/mIQTEAqS#sGiNbFVcHoNwIK9C_YKnUhfIVT3sSnAzarIykrxu1hw
https://mega.nz/file/nVI3TACT#HT6a_--Fg1hqtoOQyuKhIpnujGfPa4H0YXfZK4Xy_I0

Let me know if there is any problem or the results are very different from the paper.

**Comment by Sissuire** [comment]
@jarikorhonen Thanks. This will definitely help a lot. BTW, have you ever examined the performance on other VQA databases? (for example, CVD2014) The experimental demonstration seems not enough if there're only two databases.

**Comment by jarikorhonen** [comment]
@Sissuire No, I only tried KoNViD-1k and LIVE VQC. Apart from YouTube UGC, they are the largest natural video databases available for download at the moment. CVD2014 is not very large, and I think it's not in the internet any longer.

**Comment by Sissuire** [comment]
@jarikorhonen Thanks.
