### ISSUE TITLE
The paper ：Blind Natural Video Quality Prediction 

### ISSUE THREAD

**Issue by ciwei123** [jarikorhonen/cnn-tlvqm#3]
@jarikorhonen  Thanks for your sharing. I want to read the paper《Blind Natural Video Quality Prediction via Statistical Temporal Features and Deep Spatial Features》,but  I can't download from ACM.Could you share the paper for me ? Or,Could you show the  the comparison of TLVQM and cnn-TLVQM?  Thank you very much!!

**Comment by jarikorhonen** [comment]
@ciwei123 You can download from [here](https://mega.nz/file/LRpkyQ5J#4BKVJvJyiPw8XnQYYB5niAvPp7gMkzjCs4cnG_f5XPg).

**Comment by ciwei123** [comment]
> @ciwei123 You can download from [here](https://mega.nz/file/LRpkyQ5J#4BKVJvJyiPw8XnQYYB5niAvPp7gMkzjCs4cnG_f5XPg).

@jarikorhonen Thanks for your reply.But I can't open the link: https://mega.nz/. Could you share it by BaiduDisk or google drive?Thank you very much!!

**Comment by jarikorhonen** [comment]
@ciwei123  https://drive.google.com/file/d/1hwCdkIElzPcR_vGUT7DiPy4yb-0INnAJ/view?usp=sharing
