### ISSUE TITLE
How to calculate the number of parameters and FLOPs inside the trained CNN model?

### ISSUE THREAD

**Issue by SuperBruceJia** [jarikorhonen/cnn-tlvqm#4]
Dear Jari,

Thanks a lot for your work. It helps me a lot.

One thing I wanna inquire about is the calculation of the `number of parameters` and `FLOPs` inside the CNN model?
Is there an easy way to calculate? 

Thanks a lot and have a nice day!

Best,

Shuyue

**Comment by jarikorhonen** [comment]
Hi Shuye,

For a small network you can just use analyzeNetwork() Matlab function and check the number of learnable parameters for each layer to compute the total number of parameters. For a large network it may be necessary to write a script. 

About the FLOPs, I don't think there is any easy way to calculate. Maybe there are scripts available to compute the number of parameters and FLOPs in the internet already, I'm not sure.

Best, 
Jari

**Comment by SuperBruceJia** [comment]
> Hi Shuye,
> 
> For a small network you can just use analyzeNetwork() Matlab function and check the number of learnable parameters for each layer to compute the total number of parameters. For a large network it may be necessary to write a script.
> 
> About the FLOPs, I don't think there is any easy way to calculate. Maybe there are scripts available to compute the number of parameters and FLOPs in the internet already, I'm not sure.
> 
> Best,
> Jari

**Comment by SuperBruceJia** [comment]
> Hi Shuye,
> 
> For a small network you can just use analyzeNetwork() Matlab function and check the number of learnable parameters for each layer to compute the total number of parameters. For a large network it may be necessary to write a script.
> 
> About the FLOPs, I don't think there is any easy way to calculate. Maybe there are scripts available to compute the number of parameters and FLOPs in the internet already, I'm not sure.
> 
> Best,
> Jari

Dear Jari,

Thanks a lot for your reply. I really appreciate it.

And thanks for your advice w.r.t. the `analyzeNetwork()` function. I used it and calculated the total number of learnable parameters inside the Network without the first 37 layers.

The number of parameters is 

32896+256+147584+256+66048+131584+1024+1024+65664+256+147584+256+66048+1024+65664+256+147584+256+66048+1024+65664+256+147584+256+66048+1024+131328+512+590080+512+263168+525312+2048+2048+262400+512+590080+512+263168+2048+262400+512+590080+512+263168+2048+262400+512+590080+512+263168+2048+262400+512+590080+512+263168+2048+262400+512+590080+512+263168+2048+524800+1024+2359808+1024+1050624+2099200+4096+4096+1049088+1024+2359808+1024+1050624+4096+1049088+1024+2359808+1024+1050624+4096+262272+645=**23570693** ≈ **23.57M**

(P.S. I also added the learnable parameters in the Batch Normalization Layer.)


Meanwhile, the num of parameters of the original ResNet is **25.56M** compared to your model **23.57M** trainable parameters. 

However, as for the `Multiply-accumulate Operations (MACC/MACs)` or `FLOPs`, I just used that of the ResNet since you just modified a few layers of the original ResNet and the input dimension is the same as the ResNet, i.e., 224 X 224 X 3. So I took the advice from [convnet-burden](https://github.com/albanie/convnet-burden#image-classification-architectures) and used **4.12 G MACs**. 

![image](https://user-images.githubusercontent.com/31528604/124526573-dd28be80-de35-11eb-955b-6fe0a02d6ab0.png)
(Be a reminder that the FLOPs in this picture should be MACs rather than FLOPs, Please check the [thop](https://pypi.org/project/thop/).)

![image](https://user-images.githubusercontent.com/31528604/124535569-eb340a80-de48-11eb-806a-ce2ab95bf4cd.png)

So, as for the number of `FLOPs`, it should be approximately twice as many as the num of MACs, i.e., **8.24 G FLOPs**.

Thanks again for your help.

Best,

Shuyue
